{{- range $key, $service := .Values.services }}
{{- if ne $service.name "gateway-service" }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: crm-db-secret
  namespace: {{ $service.namespace }}

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "{{ $.Values.secrets.rds.objectName }}"
        objectType: "{{ $.Values.secrets.rds.objectType }}"
        jmesPath:
          - path: username
            objectAlias: DB_USER
          - path: password
            objectAlias: DB_PASSWORD

  secretObjects:
    - secretName: crm-db-secret
      type: Opaque
      data:
        - objectName: DB_USER
          key: DB_USER
        - objectName: DB_PASSWORD
          key: DB_PASSWORD

---
{{- end }}
{{- end }}
