apiVersion: v1
kind: Service

metadata:
  name: user-service
  namespace: user

  labels:
    app: user-service
    component: backend

spec:

  type: ClusterIP

  selector:
    app: user-service

  ports:

    - name: http
      protocol: TCP
      port: 8082
      targetPort: http
